### ISSUE TITLE
Rearrangement of Components

### ISSUE THREAD

**Issue by jmir828** [jmir828/Hang-man#3]
Some items within the main Hangman game need to be rearranged to look more like our version 1. Other layouts are also fine, just cannot keep the one that is currently there. 

High Score Labels not present.
They must still be added in: Final Score Display, High Score button in Main Menu

**Comment by akasyaa** [comment]
I'm not sure how the scores are being kept, can't figure out what to do with displaying what isn't being saved

**Comment by jmir828** [comment]
I don't think we have to add in dynamic high scores window just yet. That might be part of Checkpoint 3

For now, I just wanted to put placeholder values where scores would normally be displayed.
